### ISSUE TITLE
How do I specify a deployment request number?

### ISSUE THREAD

**Issue by ghost** [planetscale/deploy-deploy-request-action#1]
Thanks for deploy-deploy-request-action.

What I actually need should be the number of the deploy request, but the documentation says to specify the branch name.

```yaml
name: Deploy a deploy request
on:
  pull_request:
    types: [closed]

jobs:
  deploy_deploy_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Deploy a deploy request
        uses: planetscale/deploy-deploy-request-action@v1
        with:
          org_name: bmorrison-ps
          database_name: recipes_db
          branch_name: dev # 👈
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
```

I would like to specify the number of the deploy request in some way, can you give me an example of how to achieve this?

- Refer to the deploy request number output by [create deploy request action](https://github.com/planetscale/create-deploy-request-action)?
- Get the latest deploy request number?
